import pyautogui
from time import sleep
with open('automacoes finalizadas/Automacao processo fibra/csv/cad colete.csv','r') as arquivo:
    for linha in arquivo:
        item = linha.split(';')[0]
        itemc = linha.split(';')[1]
        descricao = linha.split(';')[2]
        pcorigem = linha.split(';')[3]
        #img1 = pyautogui.locateOnScreen('automacoes finalizadas/Automacao processo fibra/Imagens mapeadas/cod3.png')
        # = pyautogui.center(img1)
        pyautogui.moveTo(203,190,0.5)
        pyautogui.doubleClick()
        pyautogui.write(item)
        img2 = pyautogui.locateOnScreen('automacoes finalizadas/Automacao processo fibra/Imagens mapeadas/dup.png')
        edit_but2 = pyautogui.center(img2)
        pyautogui.moveTo(edit_but2,duration=0.5)
        pyautogui.click()
        pyautogui.sleep(0.5)
        pyautogui.write(item)
        pyautogui.sleep(0.5)
        pyautogui.press('enter')
        pyautogui.sleep(0.5)
        pyautogui.write(itemc)
        pyautogui.sleep(0.5)
        img3 = pyautogui.locateOnScreen('automacoes finalizadas/Automacao processo fibra/Imagens mapeadas/avancar.png')
        edit_but3 = pyautogui.center(img3)
        pyautogui.moveTo(edit_but3,duration=0.5)
        pyautogui.click()
        pyautogui.sleep(0.5)
        pyautogui.press('enter')
        pyautogui.press('enter')
        pyautogui.sleep(0.5)
        pyautogui.write('4')
        pyautogui.sleep(0.5)
        pyautogui.press('tab')
        pyautogui.sleep(0.5)
        pyautogui.write('4')
        img4 = pyautogui.locateOnScreen('automacoes finalizadas/Automacao processo fibra/Imagens mapeadas/pcorigem (2).png')
        edit_but4 = pyautogui.center(img4)
        pyautogui.moveTo(edit_but4,duration=0.5)
        pyautogui.click()
        pyautogui.write(pcorigem)
        img3 = pyautogui.locateOnScreen('automacoes finalizadas/Automacao processo fibra/Imagens mapeadas/avancar.png')
        edit_but3 = pyautogui.center(img3)
        pyautogui.moveTo(edit_but3,duration=0.5)
        pyautogui.click()
        pyautogui.sleep(0.5)
        pyautogui.press('enter')
        pyautogui.press('enter')
        pyautogui.press('enter')
        pyautogui.press('enter')
        pyautogui.press('enter')
        pyautogui.press('down')
        pyautogui.press('enter')
        pyautogui.press('enter')
        pyautogui.press('up')
        pyautogui.press('enter')
        pyautogui.press('up')
        pyautogui.press('enter')
        pyautogui.press('enter')
        pyautogui.press('enter')
        pyautogui.press('enter')
        pyautogui.press('enter')
        pyautogui.press('up')
        img5 = pyautogui.locateOnScreen('automacoes finalizadas/Automacao processo fibra/Imagens mapeadas/2023-08-08 13_30_31-Promob - SRVERP - Conexão de Área de Trabalho Remota.png')
        edit_but5 = pyautogui.center(img5)
        pyautogui.moveTo(edit_but5,duration=0.5)
        img6 = pyautogui.locateOnScreen('automacoes finalizadas/Automacao processo fibra/Imagens mapeadas/cadastrar.png')
        edit_but6 = pyautogui.center(img6)
        pyautogui.moveTo(edit_but6,duration=0.5)
        pyautogui.click()
        pyautogui.sleep(3)
        pyautogui.press('enter')
        img7 = pyautogui.locateOnScreen('automacoes finalizadas/Automacao processo fibra/Imagens mapeadas/SAIR.png')
        edit_but7 = pyautogui.center(img7)
        pyautogui.moveTo(edit_but7,duration=0.5)
        pyautogui.click()
        pyautogui.sleep(0.6)
        img8 = pyautogui.locateOnScreen('automacoes finalizadas/Automacao processo fibra/Imagens mapeadas/complemento.png')
        edit_but8 = pyautogui.center(img8)
        pyautogui.moveTo(edit_but8,duration=0.5)
        pyautogui.click()
        pyautogui.press('enter')
        pyautogui.press('enter')
        pyautogui.write(itemc)
        img9 = pyautogui.locateOnScreen('automacoes finalizadas/Automacao processo fibra/Imagens mapeadas/comportamento.png')
        edit_but9 = pyautogui.center(img9)
        pyautogui.moveTo(edit_but9,duration=0.5)
        pyautogui.click()
        pyautogui.sleep(0.6)
        img10 = pyautogui.locateOnScreen('automacoes finalizadas/Automacao processo fibra/Imagens mapeadas/configuracao.png')
        edit_but10 = pyautogui.center(img10)
        pyautogui.moveTo(edit_but10,duration=0.5)
        pyautogui.doubleClick()
        pyautogui.write('2')
        pyautogui.press('F2')
        pyautogui.sleep(0.8)
        pyautogui.press('enter')
        pyautogui.sleep(0.8)
        pyautogui.press('right')
        pyautogui.sleep(0.8)
        pyautogui.press('enter')
        pyautogui.sleep(0.8)
        pyautogui.press('enter')
        pyautogui.sleep(0.8)
        pyautogui.press('delete')
        pyautogui.write(descricao)
        pyautogui.sleep(0.8)
        pyautogui.press('F2')
        pyautogui.sleep(0.8)
        pyautogui.press('enter')
        pyautogui.sleep(0.8)
        pyautogui.press('right')
        pyautogui.sleep(0.8)
        pyautogui.press('enter')
        pyautogui.sleep(0.8)
        img11 = pyautogui.locateOnScreen('automacoes finalizadas/Automacao processo fibra/Imagens mapeadas/agrupamentos.png')
        edit_but11 = pyautogui.center(img11)
        pyautogui.moveTo(edit_but11,duration=0.5)
        pyautogui.sleep(0.8)
        pyautogui.click()
        pyautogui.sleep(1)


